### ISSUE TITLE
有具体的流程么？

### ISSUE THREAD

**Issue by qq596670409** [coderpage/Mine#10]
看到以下几个模块，不太懂
![image](https://user-images.githubusercontent.com/13044312/32217635-9de2ba1e-be63-11e7-9401-b0fbad71defd.png)

**Comment by liuchao0206** [comment]
@qq596670409 

`app` 是应用的主要逻辑模块，所有的界面都写在这个模块里；

`base` 里写的是一些基础类，像一些工具类等等，app 模块 和 framework 模块 都会引用这个模块；

`buildSrc` 实现的是发布应用的逻辑，实际上是一个 gradle 的插件，可以不用看；

`framework` 里实现的是一些框架定义，这个应用用的是 MVP 模式，关于 MVP 的一些定义都在这里，全局使用的一个线程池也在这里；app 模块会引用这个 framework

`gradle` 是啥就不解释了；

`libupdate` 实现的是检测更新功能的代码，在 app 中应用；
